# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jared Nance
role: Full Stack Software Engineer
email: jaredcnance@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A living documentation of my programming experiences and challenges.
  My current stacks include: .Net, Ruby, JavaScript, SQL and PostgreSql.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nance.io" # the base hostname & protocol for your site
twitter_username: jaredcnance
github_username:  jaredcnance

# Build settings
markdown: kramdown
future: false